servicegroup = {'ns11': 'http://www.tmax.co.kr/proobject/servicegroup',
                'ns21': 'http://www.tmax.co.kr/proobject/contents',
                'ns2':"http://www.tmaxsoft.co.kr/proobject/testsuite",
                'ns3':"http://www.tmax.co.kr/proobject/resource", 
                'ns4':"http://www.tmax.co.kr/proobject/message",
                'ns5':"http://www.tmax.co.kr/proobject/flow",
                'ns6':"http://www.tmax.co.kr/proobject/serviceobject",
                'ns7':"http://www.tmax.co.kr/proobject/bizobject",
                'ns8':"http://www.tmax.co.kr/proobject/dataobjectfactory",
                'ns9':"http://www.tmax.co.kr/proobject/dataobject",
                'ns10':"http://www.tmax.co.kr/proobject/dto",
                'ns11':"http://www.tmax.co.kr/proobject/dto/validator",
                'ns12':"http://www.example.org/externalObjectConfig",
                'ns13':"http://www.tmax.co.kr/proobject/testcase",
                'ns14':"http://www.tmax.co.kr/proobject/servicegroup",
                'ns15':"http://www.tmax.co.kr/proobject/mapping",
                'ns16':"http://www.tmax.co.kr/proobject/application/runtime",
                'ns17':"http://www.tmax.co.kr/proobject/serviceobject-automatic",
                'ns18':"http://www.tmax.co.kr/proobject/sourcecode",
                'ns19':"http://www.tmax.co.kr/proobject/aspectj",
                'ns20':"http://www.tmax.co.kr/probatch/jobobject",
                'ns21':"http://www.tmax.co.kr/proobject/prominer",
                'ns22':"http://www.tmax.co.kr/proobject/contents",
                'ns23':"http://www.tmax.co.kr/proobject/property",
                'ns24':"http://www.tmaxsoft.co.kr/proobject/testresult",
                'ns25':"http://www.tmax.co.kr/proobject/siteConfig",
                'ns26':"http://www.example.org/testData",
                'ns27':"http://www.tmax.co.kr/proobject/serverConfig",
                'ns28':"http://www.tmax.co.kr/proobject/probuilder_config",
                'ns29':"http://www.tmaxsoft.co.kr/proobject/testOperation",                }
 
dto={'ns2' :"http://www.tmax.co.kr/proobject/application/runtime",
        'ns3' :"http://www.tmax.co.kr/proobject/message",
        'ns4' :"http://www.tmax.co.kr/proobject/dto",
        'ns5' :"http://www.tmax.co.kr/proobject/dto/validator",
        'ns6' :"http://www.tmax.co.kr/proobject/flow",
        'ns7' :"http://www.tmax.co.kr/proobject/serviceobject",
        'ns8' :"http://www.tmax.co.kr/proobject/bizobject",
        'ns9' :"http://www.tmax.co.kr/proobject/dto",
        'ns10':"http://www.tmax.co.kr/proobject/dataobject",
        'ns11':"http://www.tmax.co.kr/proobject/testcase",
        'ns12':"http://www.tmax.co.kr/proobject/serviceobject-automatic",
        'ns13':"http://www.tmax.co.kr/proobject/sourcecode",
        'ns14':"http://www.tmax.co.kr/proobject/resource",
        'ns15':"http://www.tmax.co.kr/probatch/jobobject",
        'ns16':"http://www.tmax.co.kr/proobject/aspectj",
        'ns17':"http://www.tmax.co.kr/proobject/servicegroup",
        'ns18':"http://www.tmax.co.kr/proobject/mapping",
        'ns19':"http://www.tmaxsoft.co.kr/proobject/testsuite",
        'ns20':"http://www.example.org/externalObjectConfig",
        'ns21':"http://www.tmax.co.kr/proobject/dbio-config",
        'ns22':"http://www.tmax.co.kr/proobject/property",
        'ns23':"http://www.tmaxsoft.co.kr/proobject/testOperation",
        'ns24':"http://www.tmax.co.kr/proobject/probuilder_config",
        'ns25':"http://www.tmax.co.kr/proobject/serverConfig",
        'ns26':"http://www.example.org/testData",
        'ns27':"http://www.tmaxsoft.co.kr/proobject/testresult",
        'ns28':"http://www.tmax.co.kr/proobject/siteConfig"}

#
